### ISSUE TITLE
Disabling periodic jobs does not stop the job from being called

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#1071]
- [x] I confirm that I'm a developer of FDM Monster and allowed to use this template.

- **Description**
Disabling periodic jobs should work fine, but it does not.
https://github.com/fdm-monster/fdm-monster/blob/124b356b2b782c8923daef680fd75e3b38bf4efc/server/services/task-manager.service.js#L177

**Comment by mkevenaar** [comment]
Will be picked up in the new task system
