### ISSUE TITLE
Printer disappears after placing on dashboard

### ISSUE THREAD

**Issue by tideline3d** [fdm-monster/fdm-monster#1670]
I have two printers configured right now and when I add one of them to the dashboard, it just disappears.   The UI thinks I've placed it, but it does not show up in its placement. 

Here's a screen recording of it happening.   I've deleted and re-added the Dev1 printer a couple times now and it's still doing this.   The printer is connected and testing fine in the UI (I cut that off in the screen recording).  

Of note, both printers have a 'sort index' of 1 in the printer list screen.  

https://user-images.githubusercontent.com/12903320/234701800-9a199af0-1292-4a68-99d1-9e5baaee2606.mov

**Comment by ndarrow** [comment]
I have similar problem but not exactly the same. See attached image. 
I can place any printer in the 16 grid locations seen with printers, but I get the disappearing printer problem in any of the other locations (yellow lines).


![image](https://user-images.githubusercontent.com/91099282/234705799-2eddd188-1b84-44ad-b829-1eab3a37d38a.png)

**Comment by davidzwa** [comment]
@ndarrow I've found the issue you're experiencing and will solve it immediately. The main problem in this issue is more complex, so will need more figuring out.

**Comment by davidzwa** [comment]
@tideline3d as stated in Discord I've found the issue 

Quote from Discord: "It's simply due to removing printers that were placed on a floor. MongoDB does not perform ForeignKey checks so leaves behind orphans (as you correctly stated)"

Will fix asap.

**Comment by davidzwa** [comment]
The problems that occur are:
- Any ID can be added as a Printer on a Floor (existing or not)
- Printers can be placed on the same floor location (same coordinates)
- The printer removal action is not cascaded to other models like Floor

**Comment by davidzwa** [comment]
Fixed in version `1.3.1-rc1` which is rolling out as we speak.

**Comment by davidzwa** [comment]
@all-contributors please add @ndarrow for bug

**Comment by davidzwa** [comment]
@all-contributors please add @ndarrow for financial
