### ISSUE TITLE
Docs Link Leads to 404

### ISSUE THREAD

**Issue by lucian151** [fdm-monster/fdm-monster#1719]
**Describe the bug**
When I visit https://docs.fdm-monster.net/guides/ I get a 404 page not found warning

**To Reproduce**
Click this [link](https://docs.fdm-monster.net/guides/)
>
>

**Comment by lucian151** [comment]
Sorry this ticket is a little lackluster, wasn't sure what else to say - short and sweet!

**Comment by davidzwa** [comment]
@lucian151 thanks for the report! The build of github pages will complete soon https://github.com/fdm-monster/fdm-monster/actions/runs/4880673630

**Comment by davidzwa** [comment]
@all-contributers add @lucian151 for bug

**Comment by davidzwa** [comment]
@all-contributors add @lucian151 for bug
