### ISSUE TITLE
Batch Reprint takes an incorrect file [needs 1.4.0 verification]

### ISSUE THREAD

**Issue by WindArrow3d** [fdm-monster/fdm-monster#1773]
**Describe the bug**

When using the Batch Reprint function, printer will begin printing the wrong file.

**To Reproduce**
> Print a file- not using Batch Reprint (File A)
> Print another file- not using Batch Reprint (File B)
> Use Batch reprint in attempt to reprint File B (File A will start instead)

I have not 100% confirmed this exact behavior. I will need to do more testing to know for sure. 

**Expected behavior**
>Batch Reprint starts the last file attempted. 

**Screenshots**
>Fig A shows the versions I'm running
![image](https://github.com/fdm-monster/fdm-monster/assets/91099282/dadb4a15-bfa8-4d99-8468-7678e18aa85c)

**Browser (please complete the following information):**
 - Windows
 
 - Chrome
 
 - Version [1.1.0, etc.]
 - See Fig A
 - Your server's version is: 1.3.5
 - Your clients's version is: 1.1.2
 - Your MonsterPi version is: 0.2.0

**Additional context**

>I need to confirm this, but this is what I think is happening, from the perspective of 1 printer:

Time: 00:00 Print A started
Time: 00:55 Print A completed

Time: 01:00 Print B started
Time: 01:55 Print B completed 

Time: 02:00 Batch Reprint- Print A started

**Comment by davidzwa** [comment]
Just making it known that we have had signals that this issue still exists in 1.4.0. Therefore Im moving it to 1.4.3
