### ISSUE TITLE
Allow connecting to webcam stream

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#1893]
After 2 years, I've budged. Lets go.

**Comment by doucettom** [comment]
Following

**Comment by davidzwa** [comment]
Features and design aspects that are currently being discussed:
- Low res thumbnails or low speed preview + click to show full stream
- Standalone camera stream (not OctoPrint/OctoPi dependent) next to OctoPi stream
- WebRTC and RTSP support
- (Optional) defining camera groups or list pagination to avoid overloading the UI
- Resolution and bandwidth warnings (or maybe hard caps above 15?) in the UI

**Comment by davidzwa** [comment]
**OctoFarm's relevant code**
Snapshot with MJPEG library:
https://github.com/OctoFarm/OctoFarm/blob/206e659eee23833011798b80946ee4ddcd34aaf5/server/services/printers/mjpeg-decoder.service.js#L39

Indirection factory
https://github.com/OctoFarm/OctoFarm/blob/206e659eee23833011798b80946ee4ddcd34aaf5/server/cache/mjpeg-proxy.cache.js#L5

CamURL property per printer:
https://github.com/OctoFarm/OctoFarm/blob/206e659eee23833011798b80946ee4ddcd34aaf5/server/models/Printer.js#L13

Route to 'proxy' (directly request) a camera:
https://github.com/OctoFarm/OctoFarm/blob/206e659eee23833011798b80946ee4ddcd34aaf5/server/routes/camera-proxy.routes.js#L17

**UI side**

Aspect ratio settings based classes that are applied to a lazy-loaded img with src:
https://github.com/OctoFarm/OctoFarm/blob/206e659eee23833011798b80946ee4ddcd34aaf5/client/js/templates/camera.template.js#L5
- Different ratio's defined as css classes https://github.com/OctoFarm/OctoFarm/blob/f22996b739b4c2285e7d342a026e86058d91c519/client/css/octofarm.css#L39
- Rotation setting applied as style transform (flipH, flipV, rotate90)

Camera utility:
https://github.com/OctoFarm/OctoFarm/blob/master/client/js/utils/octofarm.utils.js#L95
- Escapes no camURL as empty URL (black image I suppose) if there is no job/thumbnail
- Escapes no camURL as thumbail fallback if there is a thumbnail and job
- Draws camera URL image if there is a camURL
