### ISSUE TITLE
Introduce quick reconnect flag

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#1961]
There are situations where quick reconnect is nice:
- creating or updating a printer
- refreshing a socket explictly

We should add a boolean flag that does not fire 'resetSocketState', which results in  apiState === API_STATE.unopened and therefore results in staggered/delayed reconnect (debounced and batched task scheduled every 15 seconds instead of every second).

**Comment by mkevenaar** [comment]
This has been solved in a different way.
