### ISSUE TITLE
Split off installations to a separate repository

### ISSUE THREAD

**Issue by davidzwa** [fdm-monster/fdm-monster#1996]
I've noticed the installations/deployments are nested in the repository causing the repo to be cloned inside the repo (edge case).
Also I've been confronted with the fact that the scripts should be standalone and reusable in f.e. MonsterPi which is already a separate repo.
Finally, it is beneficial to provide generic scripts for linux service, windows service, docker, chocolatey, RPM/deb and NPM in one place with separate versioning compared to MonsterPi and FDM Monster (server).

Would really appreciate help on this issue!

**Comment by mkevenaar** [comment]
There are currently no plans to implement this in FDM Monster.

Installations have been rewritten and partially unsupported.
