### ISSUE TITLE
Importing Printers Does Not Auto Refresh After Import

### ISSUE THREAD

**Issue by tophattwaffle** [fdm-monster/fdm-monster#2001]
**To Reproduce**

1. Import printers from Octofarm
2. Paste Octofarm JSON
3. Click Create
4. Page won't show new printers until you leave the page and come back.

https://github.com/fdm-monster/fdm-monster/assets/6774125/91c1d0bd-6c96-4abc-93dc-a385311dfb20

**Comment by davidzwa** [comment]
Same here, I think I have an idea. I'll validate an import test to exclude docker and mongodb startup issues. If that's not the issue, I'll get back to you here.
