### ISSUE TITLE
[Edge case, down-time] printing OctoPrint repeated timeouts on connection attempts due other OctoPrints being offline (overburdened server)

### ISSUE THREAD

**Issue by WindArrow3d** [fdm-monster/fdm-monster#2020]
**Describe the bug**
Printers will randomly lose connection, and eventually regain connection.

**To Reproduce**
>Watch printer tiles and wait. 

**Expected behavior**
>No connection loss. 

**Screenshots**
>No screenshots of the issue will be helpful. 
![image](https://github.com/fdm-monster/fdm-monster/assets/91099282/a69b1c25-bb01-4304-9fc9-0d9c0333f70a)

**Browser (please complete the following information):**
Browser: Chrome Version 114.0.5735.199
FDM Monster Client Version: 1.2.4
FDM Monster Server Version: 1.4.1
FDM Monster Hardware: RPi 4 8GB
FDM Monster Hardware OS: MonsterPi 0.2.2

**Additional context**

>There are other bugs that are possibly related that I will be submitting shortly.
>In my case, I have 2 printers connected and these are where I'm seeing the issues, and 54 printers manually disconnected (no power to printer or pi).

**Comment by davidzwa** [comment]
I think what you're describing here is the disconnected/powered-down printer tiles. Am I correct?

If so I would propose to change the title to: "printer tiles are toggling continuously, even though nothing seems to be changing and no connection restored".

**Comment by WindArrow3d** [comment]
1. Before connection loss: Tile shows "Printing" as normal. 
2. After connection loss: Tile shows "Unset" (see pic).
3. Once connection is restored: Tile shows "Printing" as normal. 

No user inputs from the time the tile shows "Printing", then "Unset", then "Printing" again.  


![image](https://github.com/fdm-monster/fdm-monster/assets/91099282/52c0c498-7adc-424e-b6d0-355f6dfc864e)

**Comment by davidzwa** [comment]
I believe you are correct in your conclusions. I have strong belief it's a backend issue related to the feature request in #2028.

Will keep this open as a backend regression! Thank you 🥇

**Comment by davidzwa** [comment]
We've worked on this in DM and fixed the issues accordingly. #2051 did contribute albeit only partly.
