### ISSUE TITLE
 Test Connection button doesn't seem to work anymore

### ISSUE THREAD

**Issue by WindArrow3d** [fdm-monster/fdm-monster#2021]
**Describe the bug**

the Test Connection button (side panel>Settings>test Connection) doesn't seem to be working- or at least nothing pops up under the "Checks:" heading.

**To Reproduce**
>Navigate to the Test Connection button (side panel>Settings>test Connection)
>Press the button
>Watch the "Checks:" heading appear and expand the window
>Watch nothing populate under the "Checks:" heading.

**Expected behavior**
>In previous versions a list of connection checks/statuses would display. 

**Screenshots**
![image](https://github.com/fdm-monster/fdm-monster/assets/91099282/87f996b0-765d-43e3-aba5-4234d89003c9)

![image](https://github.com/fdm-monster/fdm-monster/assets/91099282/606cd91e-07f1-4a6c-aaaf-4409fe03c3e5)

**Browser (please complete the following information):**
Browser: Chrome Version 114.0.5735.199
FDM Monster Client Version: 1.2.4
FDM Monster Server Version: 1.4.1
FDM Monster Hardware: RPi 4 8GB
FDM Monster Hardware OS: MonsterPi 0.2.2

**Additional context**
>There are other bugs that are possibly related that I will be submitting shortly.
>In my case, I have 2 printers connected and these are where I'm seeing the issues, and 54 printers manually disconnected (no power to printer or pi).

**Comment by davidzwa** [comment]
Same situation: I've created one issue to tune the server to deal with the situation at hand. Closing for clarity. #2028 

The test panel is dependent on the server emitting SocketIO events. If the server has no event-loop time left, it is not able to do this properly. This causes no test events to be returned.

My description of the problem at hand:
> MonsterPi is sweating hard to restore connections causing the FDM Monster to barely have any breathing room to do other tasks. This breathing room is called the 'event loop' in NodeJS.
If there's no time in this server event loop to serve the webpage or provide data, you will start to experience erroneous behavior. Sadly in the current FDM Monster Client this also results in freezes, but that is a separate UI issue.
