### ISSUE TITLE
Side bar file loading sometimes doesn't load

### ISSUE THREAD

**Issue by WindArrow3d** [fdm-monster/fdm-monster#2022]
**Describe the bug**

When opening the right-side bar, sometimes the files won't load and the loading bar animation goes on forever.

**To Reproduce**
>Open the right-side bar and wait for files to load/not load.
> This is really hit or miss. 

**Expected behavior**
>files load after a few moments. 

**Screenshots**
![image](https://github.com/fdm-monster/fdm-monster/assets/91099282/43a18b25-2b39-4b7c-87b9-3518e89c1ec9)

![image](https://github.com/fdm-monster/fdm-monster/assets/91099282/90fa08a8-69b4-480c-bb9b-0bd2bd5a00ab)

**Browser (please complete the following information):**
Browser: Chrome Version 114.0.5735.199
FDM Monster Client Version: 1.2.4
FDM Monster Server Version: 1.4.1
FDM Monster Hardware: RPi 4 8GB
FDM Monster Hardware OS: MonsterPi 0.2.2

**Additional context**
>There are other bugs that are possibly related that I will be submitting shortly.
>In my case, I have 2 printers connected and these are where I'm seeing the issues, and 54 printers manually disconnected (no power to printer or pi).

**Comment by davidzwa** [comment]
I've created one issue to tune the server to deal with the situation at hand. Closing for clarity.

My description of the problem at hand:
> MonsterPi is sweating hard to restore connections causing the FDM Monster to barely have any breathing room to do other tasks. This breathing room is called the 'event loop' in NodeJS.
If there's no time in this server event loop to serve the webpage or provide data, you will start to experience erroneous behavior. Sadly in the current FDM Monster Client this also results in freezes, but that is a separate UI issue.
