### ISSUE TITLE
Server Upgrade Shell Script doesn't work (linux standalone service)

### ISSUE THREAD

**Issue by doucettom** [fdm-monster/fdm-monster#2063]
tdoucet@fdm-monster:~/fdm-monster/installations/fdm-monster-node-linux$ sudo bash ./update-fdm-monster.sh

[sudo] password for tdoucet: 
[1/6] Installing latest stable tag: 1.4.4
[2/6] Stopping FDM Monster before an update

> fdm-monster-daemon@1.0.0 uninstall
> node ./uninstall-fdm-monster.js

Using default mode: systemd
./update-fdm-monster.sh: line 58: pushd: ../fdm-monster/server/: No such file or directory

Running Ubuntu Server 22.04 and fdmmonster 1.4.4

**Comment by davidzwa** [comment]
I can confirm this is broken! Thanks for the report.

We also discussed #1896 and there it should have been tackled more appropriately.
