### ISSUE TITLE
Cannot connect to octoprint instance when using zeroconf/link-local address

### ISSUE THREAD

**Issue by rmhenn** [fdm-monster/fdm-monster#2098]
**Describe the bug**
Attempting to Octoprint using a .local address results in a "Socket Aborted' error as well as an "API unreachable" error

**To Reproduce**

1. Begin Creating Printer
2. Add .local URL to host field, port in port field
3. Click "Test Connection" or "Create"

**Expected behavior**
> Connection is made to Octoprint API successfully

**Screenshots**
![chrome_CXgyQQzkEv](https://github.com/fdm-monster/fdm-monster/assets/22482801/67d21bd6-5640-4011-86ad-dd94cff10f7d)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 114.0.5735.134

**Additional context**
- Can confirm that connection succeeds when using IPv4 address
- Server 1.4.4 | Client 1.2.8

**Comment by davidzwa** [comment]
@all-contributors add @rmhenn for bug
@all-contributors add @rmhenn for ideas

**Comment by davidzwa** [comment]
@all-contributors add @rmhenn for bug

**Comment by wallace11** [comment]
May I add that using a port should not be mandatory.
For example, I use local reverse proxy, so all my URLs are  `https://pi.local/<PRINTER>`. fdm-monster automatically appends the port to the url which causes it to become incorrect.

**Comment by davidzwa** [comment]
Tackling this issue on the frontend as we speak. The backend will follow after.
