### ISSUE TITLE
Diagnostics Downloading Log Files Zip Generates corrupt zip-file

### ISSUE THREAD

**Issue by Chasebarn35** [fdm-monster/fdm-monster#2321]
**Describe the bug**

While attempting to pull the Log Dump, zipped files download produce an unzippable file.

**To Reproduce**
This was done utilizing the docker compose setup, along with the default documentations docker-compose.yml provided. This is on server version 1.4.5, client version 1.2.9
my docker setup went as follows
> sudo docker pull davidzwa/fdm-monster:latest
> \<creating fdmmonster directory and putting the docker-compose.yml in the directory\>
> sudo docker-compose up -d
After entering the localhost:4000, and then having issues during printer creation, attempting to download the log files was attempted, and failed. This was recreated on 2 seperate machines connected to the FDMMonster setup, which both resulted in failure 
**Expected behavior**
Zipped Log Files being able to be unzipped and viewed

**Browser (please complete the following information):**
 - OS: FDMMonster is on PopOS, External machines accessing were on Arch, and Windows
 - Browser: Firefox, Chrome
 - Version: unspecified

>

**Comment by davidzwa** [comment]
@Chasebarn35 could you share the file size of the ZIP with me?
