### ISSUE TITLE
Printers Group

### ISSUE THREAD

**Issue by doucettom** [fdm-monster/fdm-monster#2684]
There is already a floor concept but it would be nice to have printer's group (and a printer could be a member of many groups)

**Comment by davidzwa** [comment]
@doucettom that's a good idea. Could you tell me the intended goal?

I see multiple possible problems to be solved with a grouping feature:
- Easy filtering of printers in the list (allows multiple groups)
- Color coding or recognizing printers on the grid better (single group is better, or some logic around it)

Do you have more thoughts what the groups feature could help with?

Some questions:
- Are tags a more suitable approach? This is what I'm used to in cloud platforms as a more free format object correlation mechanism. This could even be shared with the floors, etc. One downside comparing a tags feature to a grouping feature, is that there cannot be a very specific design around tags as its quite generic, whereas grouping allows specific design (f.e. a colored border on the grid).

**Comment by doucettom** [comment]
Yup allow multiple groups so a single printer can be a member of many groups thus allowing fine-tuned filtering. Color-coding could be nice, I used to single-color code them within OP UI (8 colors or so) and picking up that color in FDMM would be nice as well. Tags or Groups both would work and have pretty much the same use.

**Comment by davidzwa** [comment]
Thanks for the feedback. Will ping you here when I get cracking on it.

**Comment by davidzwa** [comment]
@all-contributors add @doucettom for idea
