### ISSUE TITLE
Slicer/Cura thumbnail support

### ISSUE THREAD

**Issue by ZombiesLoveMe** [fdm-monster/fdm-monster#2890]
**Describe the solution you'd like**
When viewing the files in the pop out menu the ability to see a thumbnail of the STL file would be nice

**Comment by davidzwa** [comment]
In order to get this going I need to do some research:
- OctoPrint thumbnail availability
- Parse on upload only
- How do OctoFarm or others do it?
- Last resort: downloading the gcode (~first 500 lines) from OctoPrint and parse the thumbnail

**Comment by mkevenaar** [comment]
Duplicate of #1906
