### ISSUE TITLE
Push latest-sqlite tag

### ISSUE THREAD

**Issue by mkevenaar** [fdm-monster/fdm-monster#3069]
**Is your feature request related to a problem? Please describe.**
For easy upgradability push a latest-sqlite tag

**Describe the solution you'd like**
Tag being pushed 

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by davidzwa** [comment]
This has been automated! Dont have a PR, so I will close this by hand. Thanks for the suggestion!
