### ISSUE TITLE
Dockerfile: Add curl

### ISSUE THREAD

**Issue by mkevenaar** [fdm-monster/fdm-monster#3088]
**Is your feature request related to a problem? Please describe.**
To enhance the docker-compose structure, a health check should be added. This would be as simple as using `curl` to the HTTP port.

**Describe the solution you'd like**
Curl to be added to the docker container

Add the following like to the dockerfile
```
RUN apt-get update && apt-get install -y ca-certificates curl
```

**Describe alternatives you've considered**
NA

**Additional context**
This will increase the docker container image but will allow a docker-compose installation to automatically restart the container in case something goes wrong inside it without the user intervening.

**Comment by davidzwa** [comment]
Due to this being a significant improvement of how FDM Monster is deployed as a docker container, without being a breaking change nor impactful, I propose to schedule the issue asap.
