### ISSUE TITLE
Remove "Save" buttons, make settings fully auto-saving (remove any primary color)

### ISSUE THREAD

**Issue by mkevenaar** [fdm-monster/fdm-monster#3110]
**Describe the bug**
The current buttons are red, it screams, it suggests things are broken/bad/etc.

**To Reproduce**
NA

**Screenshots**
![image](https://github.com/fdm-monster/fdm-monster/assets/834643/63c4be6e-775d-432a-8baa-a4d2021335e4)

Suggestion to change:

(changed CSS class primary to gray)
![image](https://github.com/fdm-monster/fdm-monster/assets/834643/35c1dd6e-97c7-4c2d-abdc-ce9aaa6b2f49)

**Browser (please complete the following information):**
NA

**Additional context**
NA

**Comment by davidzwa** [comment]
Associated issue on client side (https://github.com/fdm-monster/fdm-monster-client/issues/86). 

Let's keep that one in mind when tackling this issue.

**Comment by davidzwa** [comment]
This issue is less work now. 

- Make (grid) settings self-saving
- Remove any primary color on buttons which need to be kept (autosave not possible due to complexity)
