### ISSUE TITLE
Every print job I receive Cannot read properties of null (reading 'toFixed')

### ISSUE THREAD

**Issue by clumsyzombie** [fdm-monster/fdm-monster#3141]
Current versions:
Your server's version is: 1.5.4
Your clients's version is: 1.4.4
Your MonsterPi version is: 0.3.1

Octopi version information:
OctoPrint:  Version 1.9.3
Octopi  Version 0.18.0, running on Raspberry Pi 4 Model B Rev 1.2
128 GB SD card with 100GB free 

I have a gcode that is just sliced using UltiMaker Cura 5.6.0
I go into the MonsterPi web site and tell it to "Select gcode file"
Find the gcode and then add it 
once I add it and select the printer and the code and say upload it uploads it just fine
the moment I tell it to start printing 
I get spammed with "Cannot read properties of null (reading 'toFixed')"

But the print still prints 
I have verified under my printer and tested connection everything is green. 
Also it is updating ever 1 to .5 sec and 
Name: DS-Ender3
URL: http://192.168.0.73
Host: 
responding
WebSocket: 
authenticated
Printer: 
Printing

I did leave the Default Floor details 
I am using the Application API key with the admin user.

**Comment by davidzwa** [comment]
I've verified this problem is gone and I will close this issue accordingly. Expect this to be fixed in (at least) version >=1.7
