### ISSUE TITLE
Bug when view details on printer

### ISSUE THREAD

**Issue by V4LVE** [fdm-monster/fdm-monster#3454]
**Describe the bug**
When entering the details of a printer from the floor. A 500 error occours

**To Reproduce**
> Enter details of a printer from the floor.
> 
**Expected behavior**
> No fault codes

**Screenshots**
> 
![image](https://github.com/user-attachments/assets/49d6c6d1-8c43-4bbf-a53d-bd94936fc8c7)

**Browser (please complete the following information):**
 - OS: Windows (Docker)
 - Browser: chrome
 - Version: FDMM: Latest. OctoPrint: Latest

**Comment by davidzwa** [comment]
Hi @V4LVE can you tell me if this problem occurs regularly?

Is this OctoPrint maybe showing trouble loading its webpage or maybe its slow?
Have you tried increasing the timeout setting of FDM Monster?

And finally could you let me know if the problem persists in 1.6.4?

Thanks :)

**Comment by davidzwa** [comment]
@V4LVE eager to hear your reply.

**Comment by davidzwa** [comment]
Do to lack of response I am closing this issue. FDM Monster has had a lot of work and without further information it is hard for me to say if this issue is still present.
