### ISSUE TITLE
[Feature]: Sonoff TH Elite & POW Elite

### ISSUE THREAD

**Issue by KarelVDM** [fdm-monster/fdm-monster#3876]
### Checklist

- [X] I agree to follow our [Code of Conduct](https://github.com/fdm-monster/fdm-monster/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have verified no [other issues](https://github.com/fdm-monster/fdm-monster/issues) exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Not related to a problem. 

### Describe The Solution. Why is it needed?

Nice addition would be to have Sonoff TH & POW Elite devices show the current Power Consumption and Temp and Humidity. 
TH Elite - https://sonoff.tech/product/diy-smart-switches/th-elite/
POW Elite - https://sonoff.tech/product/diy-smart-switches/pow-elite/

Mockup attached
![Screenshot 2024-12-04 125414](https://github.com/user-attachments/assets/7fe3e4bc-2bd9-43fe-8294-4c4d59a38db2)

This way you could have an overview of the mentioned values.

**Comment by davidzwa** [comment]
Hi thanks for taking the time to elaborate the design visually.

As communicated elsewhere, I do see the value of these sensors and their integrations being necessary. I really do. Part of managing a farm is having overview on the cost/environment side of things and energy usage/climate can be an important part contributing to that side of running a 3D print farm. But I intuitively feel that building support for one or more specific sensor like the ones mentioned above might lead to outdated, lacking or unpleasant features in the future. Ive experienced this before by supporting specific OctoPrint plugins which then change causing things to break. 

I do hope that the design of FDMM might lend itself to extensibility in the future (in whatever way or form). But at this point the architecture does not lend itself to it. And with that in mind I cannot accept this feature request at this point. The project needs to get other lacking features implemented first. 

For anyone reading this, I really recommend setting up Home Assisant or a similar application for instead. And if managing an OctoPrint plugin across a farm is a bottleneck, rest assured that this is a feature request that has been planned or is being prepared (also given that we support Moonraker now, albeit technically experimentally but its getting quite stable). 
The Home Assistant direction is already proven to lead to greater extensibility.

Ill close this as unplanned! I hope my argumentation helps with understanding why.
